[workspace]
members = ["src/firecracker", "src/jailer"]
default-members = ["src/firecracker"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[patch.crates-io]
versionize = { git = "https://github.com/alexandruag/versionize.git", branch = "blob" }