[package]
name = "mmap_fork"
version = "0.1.0"
authors = ["The Firecracker & rust-vmm friendship committee"]
edition = "2018"

[dependencies]
vm-memory = { version = ">=0.2.2", features = ["backend-mmap"] }

[dev-dependencies]
vmm-sys-util = ">= 0.4.0"
