[package]
name = "verde"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
serde = { version = ">=1.0.104", features = ["derive"] }

[dev-dependencies]
bincode = ">=1.2.1"
serde_json = ">=1.0.48"